export const arabicNumbers = [
  { number: "٠", name: "صفر", value: 0 },
  { number: "١", name: "واحد", value: 1 },
  { number: "٢", name: "اثنان", value: 2 },
  { number: "٣", name: "ثلاثة", value: 3 },
  { number: "٤", name: "أربعة", value: 4 },
  { number: "٥", name: "خمسة", value: 5 },
  { number: "٦", name: "ستة", value: 6 },
  { number: "٧", name: "سبعة", value: 7 },
  { number: "٨", name: "ثمانية", value: 8 },
  { number: "٩", name: "تسعة", value: 9 },
  { number: "١٠", name: "عشرة", value: 10 },
];

export const arabicLetters = [
  { letter: "أ", name: "ألف", example: "أسد", emoji: "🦁" },
  { letter: "ب", name: "باء", example: "بطة", emoji: "🦆" },
  { letter: "ت", name: "تاء", example: "تفاح", emoji: "🍎" },
  { letter: "ث", name: "ثاء", example: "ثعلب", emoji: "🦊" },
  { letter: "ج", name: "جيم", example: "جمل", emoji: "🐪" },
  { letter: "ح", name: "حاء", example: "حصان", emoji: "🐴" },
  { letter: "خ", name: "خاء", example: "خروف", emoji: "🐑" },
  { letter: "د", name: "دال", example: "دب", emoji: "🐻" },
  { letter: "ذ", name: "ذال", example: "ذئب", emoji: "🐺" },
  { letter: "ر", name: "راء", example: "رمان", emoji: "🍇" },
  { letter: "ز", name: "زاي", example: "زرافة", emoji: "🦒" },
  { letter: "س", name: "سين", example: "سمكة", emoji: "🐟" },
  { letter: "ش", name: "شين", example: "شمس", emoji: "☀️" },
  { letter: "ص", name: "صاد", example: "صقر", emoji: "🦅" },
  { letter: "ض", name: "ضاد", example: "ضفدع", emoji: "🐸" },
  { letter: "ط", name: "طاء", example: "طائر", emoji: "🐦" },
  { letter: "ظ", name: "ظاء", example: "ظبي", emoji: "🦌" },
  { letter: "ع", name: "عين", example: "عصفور", emoji: "🐦" },
  { letter: "غ", name: "غين", example: "غزال", emoji: "🦌" },
  { letter: "ف", name: "فاء", example: "فيل", emoji: "🐘" },
  { letter: "ق", name: "قاف", example: "قطة", emoji: "🐱" },
  { letter: "ك", name: "كاف", example: "كلب", emoji: "🐕" },
  { letter: "ل", name: "لام", example: "ليمون", emoji: "🍋" },
  { letter: "م", name: "ميم", example: "موز", emoji: "🍌" },
  { letter: "ن", name: "نون", example: "نحلة", emoji: "🐝" },
  { letter: "هـ", name: "هاء", example: "هدهد", emoji: "🐦" },
  { letter: "و", name: "واو", example: "وردة", emoji: "🌹" },
  { letter: "ي", name: "ياء", example: "يد", emoji: "✋" },
];

export const animals = [
  { name: "أسد", emoji: "🦁", sound: "زئير", category: "حيوان" },
  { name: "فيل", emoji: "🐘", sound: "نهيم", category: "حيوان" },
  { name: "قطة", emoji: "🐱", sound: "مواء", category: "حيوان" },
  { name: "كلب", emoji: "🐕", sound: "نباح", category: "حيوان" },
  { name: "خروف", emoji: "🐑", sound: "ثغاء", category: "حيوان" },
  { name: "بقرة", emoji: "🐄", sound: "خوار", category: "حيوان" },
  { name: "حصان", emoji: "🐴", sound: "صهيل", category: "حيوان" },
  { name: "دب", emoji: "🐻", sound: "هدير", category: "حيوان" },
  { name: "زرافة", emoji: "🦒", sound: "همهمة", category: "حيوان" },
  { name: "قرد", emoji: "🐒", sound: "صراخ", category: "حيوان" },
  { name: "ثعلب", emoji: "🦊", sound: "عواء", category: "حيوان" },
  { name: "أرنب", emoji: "🐰", sound: "صرير", category: "حيوان" },
  { name: "عصفور", emoji: "🐦", sound: "تغريد", category: "طائر" },
  { name: "ديك", emoji: "🐓", sound: "صياح", category: "طائر" },
  { name: "بطة", emoji: "🦆", sound: "بطبطة", category: "طائر" },
  { name: "بومة", emoji: "🦉", sound: "نعيب", category: "طائر" },
  { name: "نسر", emoji: "🦅", sound: "صرصرة", category: "طائر" },
  { name: "ببغاء", emoji: "🦜", sound: "تقليد", category: "طائر" },
  { name: "حمامة", emoji: "🕊️", sound: "هديل", category: "طائر" },
  { name: "طاووس", emoji: "🦚", sound: "صراخ", category: "طائر" },
];

export const cardColors = [
  "from-rose-400 to-pink-500",
  "from-orange-400 to-amber-500",
  "from-emerald-400 to-teal-500",
  "from-cyan-400 to-blue-500",
  "from-violet-400 to-purple-500",
  "from-fuchsia-400 to-pink-500",
];

export type Section = "home" | "numbers" | "letters" | "animals";
