export const arabicNumbers = [
  { number: "٠", name: "صفر", value: 0, emoji: "✊", searchQuery: "fist zero fingers" },
  { number: "١", name: "واحد", value: 1, emoji: "☝️", searchQuery: "one finger counting" },
  { number: "٢", name: "اثنان", value: 2, emoji: "✌️", searchQuery: "two fingers counting" },
  { number: "٣", name: "ثلاثة", value: 3, emoji: "🤟", searchQuery: "three fingers counting" },
  { number: "٤", name: "أربعة", value: 4, emoji: "🖖", searchQuery: "four fingers counting" },
  { number: "٥", name: "خمسة", value: 5, emoji: "🖐️", searchQuery: "five fingers counting" },
  { number: "٦", name: "ستة", value: 6, emoji: "🖐️☝️", searchQuery: "six fingers hand counting" },
  { number: "٧", name: "سبعة", value: 7, emoji: "🖐️✌️", searchQuery: "seven fingers hand counting" },
  { number: "٨", name: "ثمانية", value: 8, emoji: "🖐️🤟", searchQuery: "eight fingers hand counting" },
  { number: "٩", name: "تسعة", value: 9, emoji: "🖐️🖖", searchQuery: "nine fingers hand counting" },
  { number: "١٠", name: "عشرة", value: 10, emoji: "👐", searchQuery: "ten fingers both hands counting" },
];

export const arabicLetters = [
  { letter: "أ", name: "ألف", example: "أسد", emoji: "🦁", searchQuery: "lion" },
  { letter: "ب", name: "باء", example: "بطة", emoji: "🦆", searchQuery: "duck" },
  { letter: "ت", name: "تاء", example: "تفاح", emoji: "🍎", searchQuery: "red apple fruit" },
  { letter: "ث", name: "ثاء", example: "ثعلب", emoji: "🦊", searchQuery: "fox" },
  { letter: "ج", name: "جيم", example: "جمل", emoji: "🐪", searchQuery: "camel" },
  { letter: "ح", name: "حاء", example: "حصان", emoji: "🐴", searchQuery: "horse" },
  { letter: "خ", name: "خاء", example: "خروف", emoji: "🐑", searchQuery: "sheep" },
  { letter: "د", name: "دال", example: "دب", emoji: "🐻", searchQuery: "bear" },
  { letter: "ذ", name: "ذال", example: "ذئب", emoji: "🐺", searchQuery: "wolf" },
  { letter: "ر", name: "راء", example: "رمان", emoji: "🍇", searchQuery: "pomegranate" },
  { letter: "ز", name: "زاي", example: "زرافة", emoji: "🦒", searchQuery: "giraffe" },
  { letter: "س", name: "سين", example: "سمكة", emoji: "🐟", searchQuery: "fish" },
  { letter: "ش", name: "شين", example: "شمس", emoji: "☀️", searchQuery: "sun" },
  { letter: "ص", name: "صاد", example: "صقر", emoji: "🦅", searchQuery: "falcon" },
  { letter: "ض", name: "ضاد", example: "ضفدع", emoji: "🐸", searchQuery: "frog" },
  { letter: "ط", name: "طاء", example: "طائر", emoji: "🐦", searchQuery: "bird" },
  { letter: "ظ", name: "ظاء", example: "ظبي", emoji: "🦌", searchQuery: "deer" },
  { letter: "ع", name: "عين", example: "عصفور", emoji: "🐦", searchQuery: "sparrow" },
  { letter: "غ", name: "غين", example: "غزال", emoji: "🦌", searchQuery: "gazelle" },
  { letter: "ف", name: "فاء", example: "فيل", emoji: "🐘", searchQuery: "elephant" },
  { letter: "ق", name: "قاف", example: "قطة", emoji: "🐱", searchQuery: "cat" },
  { letter: "ك", name: "كاف", example: "كلب", emoji: "🐕", searchQuery: "dog" },
  { letter: "ل", name: "لام", example: "ليمون", emoji: "🍋", searchQuery: "lemon" },
  { letter: "م", name: "ميم", example: "موز", emoji: "🍌", searchQuery: "banana" },
  { letter: "ن", name: "نون", example: "نحلة", emoji: "🐝", searchQuery: "bee" },
  { letter: "هـ", name: "هاء", example: "هدهد", emoji: "🐦", searchQuery: "hoopoe bird" },
  { letter: "و", name: "واو", example: "وردة", emoji: "🌹", searchQuery: "rose" },
  { letter: "ي", name: "ياء", example: "يد", emoji: "✋", searchQuery: "hand" },
];

export const englishLetters = [
  { char: "A", name: "A", example: "Apple", emoji: "🍎", searchQuery: "red apple fruit" },
  { char: "B", name: "B", example: "Ball", emoji: "⚽", searchQuery: "ball" },
  { char: "C", name: "C", example: "Cat", emoji: "🐱", searchQuery: "cat" },
  { char: "D", name: "D", example: "Dog", emoji: "🐶", searchQuery: "dog" },
  { char: "E", name: "E", example: "Egg", emoji: "🥚", searchQuery: "egg" },
  { char: "F", name: "F", example: "Fish", emoji: "🐟", searchQuery: "fish" },
  { char: "G", name: "G", example: "Goat", emoji: "🐐", searchQuery: "goat" },
  { char: "H", name: "H", example: "Hen", emoji: "🐔", searchQuery: "hen" },
  { char: "I", name: "I", example: "Ice cream", emoji: "🍦", searchQuery: "ice cream" },
  { char: "J", name: "J", example: "Jam", emoji: "🍯", searchQuery: "jam" },
  { char: "K", name: "K", example: "Kite", emoji: "🪁", searchQuery: "kite" },
  { char: "L", name: "L", example: "Lion", emoji: "🦁", searchQuery: "lion" },
  { char: "M", name: "M", example: "Monkey", emoji: "🐒", searchQuery: "monkey" },
  { char: "N", name: "N", example: "Net", emoji: "🥅", searchQuery: "net" },
  { char: "O", name: "O", example: "Orange", emoji: "🍊", searchQuery: "orange fruit" },
  { char: "P", name: "P", example: "Pen", emoji: "🖋️", searchQuery: "pen" },
  { char: "Q", name: "Q", example: "Queen", emoji: "👸", searchQuery: "queen" },
  { char: "R", name: "R", example: "Rabbit", emoji: "🐰", searchQuery: "rabbit" },
  { char: "S", name: "S", example: "Sun", emoji: "☀️", searchQuery: "sun" },
  { char: "T", name: "T", example: "Tiger", emoji: "🐯", searchQuery: "tiger" },
  { char: "U", name: "U", example: "Umbrella", emoji: "☂️", searchQuery: "umbrella" },
  { char: "V", name: "V", example: "Van", emoji: "🚐", searchQuery: "van" },
  { char: "W", name: "W", example: "Watch", emoji: "⌚", searchQuery: "watch" },
  { char: "X", name: "X", example: "X-ray", emoji: "🩻", searchQuery: "x-ray" },
  { char: "Y", name: "Y", example: "Yo-yo", emoji: "🪀", searchQuery: "yo-yo" },
  { char: "Z", name: "Z", example: "Zebra", emoji: "🦓", searchQuery: "zebra" },
];

export const englishNumbers = [
  { char: "0", name: "Zero", emoji: "✊", searchQuery: "fist zero fingers" },
  { char: "1", name: "One", emoji: "☝️", searchQuery: "one finger counting" },
  { char: "2", name: "Two", emoji: "✌️", searchQuery: "two fingers counting" },
  { char: "3", name: "Three", emoji: "🤟", searchQuery: "three fingers counting" },
  { char: "4", name: "Four", emoji: "🖖", searchQuery: "four fingers counting" },
  { char: "5", name: "Five", emoji: "🖐️", searchQuery: "five fingers counting" },
  { char: "6", name: "Six", emoji: "🖐️☝️", searchQuery: "six fingers hand counting" },
  { char: "7", name: "Seven", emoji: "🖐️✌️", searchQuery: "seven fingers hand counting" },
  { char: "8", name: "Eight", emoji: "🖐️🤟", searchQuery: "eight fingers hand counting" },
  { char: "9", name: "Nine", emoji: "🖐️🖖", searchQuery: "nine fingers hand counting" },
  { char: "10", name: "Ten", emoji: "👐", searchQuery: "ten fingers both hands counting" },
];

export const animals = [
  { name: "أسد", emoji: "🦁", sound: "زئير", category: "حيوان", searchQuery: "lion" },
  { name: "فيل", emoji: "🐘", sound: "نهيم", category: "حيوان", searchQuery: "elephant" },
  { name: "قطة", emoji: "🐱", sound: "مواء", category: "حيوان", searchQuery: "cat" },
  { name: "كلب", emoji: "🐕", sound: "نباح", category: "حيوان", searchQuery: "dog" },
  { name: "خروف", emoji: "🐑", sound: "ثغاء", category: "حيوان", searchQuery: "sheep" },
  { name: "بقرة", emoji: "🐄", sound: "خوار", category: "حيوان", searchQuery: "cow" },
  { name: "حصان", emoji: "🐴", sound: "صهيل", category: "حيوان", searchQuery: "horse" },
  { name: "دب", emoji: "🐻", sound: "هدير", category: "حيوان", searchQuery: "bear" },
  { name: "زرافة", emoji: "🦒", sound: "همهمة", category: "حيوان", searchQuery: "giraffe" },
  { name: "قرد", emoji: "🐒", sound: "صراخ", category: "حيوان", searchQuery: "monkey" },
  { name: "ثعلب", emoji: "🦊", sound: "عواء", category: "حيوان", searchQuery: "fox" },
  { name: "أرنب", emoji: "🐰", sound: "صرير", category: "حيوان", searchQuery: "rabbit" },
  { name: "عصفور", emoji: "🐦", sound: "تغريد", category: "طائر", searchQuery: "sparrow" },
  { name: "ديك", emoji: "🐓", sound: "صياح", category: "طائر", searchQuery: "rooster" },
  { name: "بطة", emoji: "🦆", sound: "بطبطة", category: "طائر", searchQuery: "duck" },
  { name: "بومة", emoji: "🦉", sound: "نعيب", category: "طائر", searchQuery: "owl" },
  { name: "نسر", emoji: "🦅", sound: "صرصرة", category: "طائر", searchQuery: "eagle" },
  { name: "ببغاء", emoji: "🦜", sound: "تقليد", category: "طائر", searchQuery: "parrot" },
  { name: "حمامة", emoji: "🕊️", sound: "هديل", category: "طائر", searchQuery: "pigeon" },
  { name: "طاووس", emoji: "🦚", sound: "صراخ", category: "طائر", searchQuery: "peacock" },
];

export const cardColors = [
  "from-rose-400 to-pink-500",
  "from-orange-400 to-amber-500",
  "from-emerald-400 to-teal-500",
  "from-cyan-400 to-blue-500",
  "from-violet-400 to-purple-500",
  "from-fuchsia-400 to-pink-500",
];
